CREATE TABLE IF NOT EXISTS PACIENTES(
    ID SERIAL PRIMARY KEY,
    CREATE INDEX IF NOT EXISTS IDX_PACIENTES_ID ON PACIENTES(ID);

CREATE TABLE IF NOT EXISTS MEDICOS(
    ID SERIAL PRIMARY KEY,
    NOMBRES VARCHAR(50) NOT NULL,
    APELLIDOS VARCHAR(50) NOT NULL,
    TELEFONO VARCHAR(15) DEFAULT '-',
    DIRECCION VARCHAR(100) DEFAULT '-',
    NUM_COLEGIADO VARCHAR(25) NOT NULL,
    CORREO VARCHAR(50) DEFAULT '-',
    ROL VARCHAR(25) DEFAULT 'user'
);

CREATE INDEX IF NOT EXISTS IDX_MEDICOS_ID ON MEDICOS(ID);

CREATE TABLE IF NOT EXISTS ESPECIALIDADES(
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL
);

CREATE INDEX IF NOT EXISTS IDX_ESPECIALIDADES_ID ON ESPECIALIDADES(ID);

CREATE TABLE IF NOT EXISTS ESPECIALIZADOS(
    MEDICO_ID INTEGER REFERENCES MEDICOS,
    ESPECIALIDAD_ID INTEGER REFERENCES ESPECIALIDADES
);

CREATE INDEX IF NOT EXISTS IDX_ESPECIALIZADOS_ID ON ESPECIALIZADOS(MEDICO_ID);

CREATE TABLE IF NOT EXISTS DEPARTAMENTOS(
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL
);

-- The departamentos table contains the names of the departments in Guatemala
CREATE TABLE IF NOT EXISTS LUGARES(
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    DIRECCION VARCHAR(250) DEFAULT '-',
    TIPO VARCHAR(10) DEFAULT 'Hospital',
    DEPARTAMENTO_ID INTEGER REFERENCES DEPARTAMENTOS
);

CREATE INDEX IF NOT EXISTS IDX_LUGARES_ID ON LUGARES(ID);

-- The lugares table contains the names of the hospitals in Guatemala
CREATE TABLE IF NOT EXISTS TRABAJOS(
    MEDICO_ID INTEGER REFERENCES MEDICOS,
    LUGAR_ID INTEGER REFERENCES LUGARES
);

CREATE TABLE IF NOT EXISTS INSUMOS(
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(25) DEFAULT '-',
    TIPO VARCHAR(10) DEFAULT 'Materiales'
);

CREATE INDEX IF NOT EXISTS IDX_INSUMOS_ID ON INSUMOS(ID);

CREATE TABLE IF NOT EXISTS INSUMOS_DEL_LUGAR(
    LUGAR_ID INTEGER REFERENCES LUGARES,
    INSUMO_ID INTEGER REFERENCES INSUMOS,
    CANTIDAD_ACTUAL INTEGER DEFAULT 0,
    CANTIDAD_INICIAL INTEGER DEFAULT 0
);

CREATE INDEX IF NOT EXISTS INSUMOS_DEL_LUGAR_IDX ON INSUMOS_DEL_LUGAR(
    LUGAR_ID,
    INSUMO_ID
);

CREATE TABLE IF NOT EXISTS TRATAMIENTOS(
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    TIPO text DEFAULT '-',
    -- Medicina / Procedimiento
    DOSIS text DEFAULT '-'
);

CREATE TABLE IF NOT EXISTS EXAMENES(
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS ENFERMEDADES(
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS ENFERMEDADES_HEREDADAS(
    PACIENTE_ID INTEGER REFERENCES PACIENTES,
    ENFERMEDAD_ID INTEGER REFERENCES ENFERMEDADES
);

CREATE INDEX IF NOT EXISTS IDX_ENFERMEDADES_HEREDADAS ON ENFERMEDADES_HEREDADAS(
    PACIENTE_ID,
    ENFERMEDAD_ID
);

CREATE TABLE IF NOT EXISTS STATUS(
    ID SERIAL PRIMARY KEY,
    STATUS VARCHAR(25) NOT NULL -- Murio / Sigue enfermo / Recuperado
);

CREATE TABLE IF NOT EXISTS CONSULTAS(
    ID SERIAL PRIMARY KEY,
    PACIENTE_ID INTEGER REFERENCES PACIENTES,
    LUGAR_ID INTEGER REFERENCES LUGARES,
    FECHA timestamp DEFAULT CURRENT_TIMESTAMP,
    OBSERVACIONES text DEFAULT '-',
    STATUS_ID INTEGER REFERENCES STATUS
);

CREATE INDEX IF NOT EXISTS IDX_CONSULTAS_PACIENTE_ID ON CONSULTAS(PACIENTE_ID);

CREATE TABLE IF NOT EXISTS TRATAMIENTOS_APLICADOS(
    CONSULTA_ID INTEGER REFERENCES CONSULTAS,
    TRATAMIENTO_ID INTEGER REFERENCES TRATAMIENTOS
);

CREATE INDEX IF NOT EXISTS IDX_TRATAMIENTOS_APLICADOS ON TRATAMIENTOS_APLICADOS(
    CONSULTA_ID,
    TRATAMIENTO_ID
);

CREATE TABLE IF NOT EXISTS EXAMENES_APLICADOS(
    CONSULTA_ID INTEGER REFERENCES CONSULTAS,
    EXAMEN_ID INTEGER REFERENCES EXAMENES
);

CREATE INDEX IF NOT EXISTS IDX_EXAMENES_APLICADOS ON EXAMENES_APLICADOS(
    CONSULTA_ID,
    EXAMEN_ID
);

CREATE TABLE IF NOT EXISTS ENFERMEDADES_DIAGNOSTICADAS(
    CONSULTA_ID INTEGER REFERENCES CONSULTAS,
    ENFERMEDAD_ID INTEGER REFERENCES ENFERMEDADES
);

CREATE INDEX IF NOT EXISTS IDX_ENFERMEDADES_DIAGNOSTICADAS ON ENFERMEDADES_DIAGNOSTICADAS(
    CONSULTA_ID,
    ENFERMEDAD_ID
);

CREATE TABLE IF NOT EXISTS MEDICOS_TRATANTES(
    CONSULTA_ID INTEGER REFERENCES CONSULTAS,
    MEDICO_ID INTEGER REFERENCES MEDICOS
);

CREATE INDEX IF NOT EXISTS IDX_MEDICOS_TRATANTES ON MEDICOS_TRATANTES(
    CONSULTA_ID,
    MEDICO_ID
);

CREATE TABLE IF NOT EXISTS BITACORA (
    ID SERIAL PRIMARY KEY,
    MEDICO_ID INTEGER REFERENCES MEDICOS,
    TABLA VARCHAR(50),
    ACCION VARCHAR(10),
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    VALORES_VIEJOS JSON,
    VALORES_NUEVOS JSON
);